fix(notebook): convert array index to int
since py3 division return float

fix error:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis
(`None`) and integer or boolean arrays are valid indices